config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  # root page
  root "static_pages#home"
  # static pages routes
  get "/help",    to: "static_pages#about", as: "helf"
  get "/about",   to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  # for new user
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  # for sign in
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # show all user's posts
  get "/user/posts/:id", to: "posts#posts", as: "user_posts"
  # error page
  get "/error", to: "static_pages#error"

  # adding REST architecture
  resources :users do
    # member return id
    # collection returns the obj
    member do
      get :following, :followers
    end
  end

  # Resources for the reset password and activation path
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new edit update create]
  resources :posts,               only: %i[create destroy]
  resources :relationships,       only: %i[create destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: %i[edit update]
  before_action :valid_user, only: %i[edit update]
  before_action :check_expiration, only: %i[edit update]

  def new; end

  def create
    @user = User.find_by(email: params[:reset_password][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = show_message :email_sent
      redirect_to login_path
    else
      flash.now[:danger] = show_message :email_not_found
      render "new"
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      @user.errors.add :password, "Can't be empty"
    elsif @user.update user_params
      log_in @user
      @user.update reset_digest: nil
      flash[:success] = show_message :success_password
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def get_user
    @user = User.find_by email: params[:email]
  end

  def valid_user
    # it's called params[:id] because it's an auto generate resource
    redirect_to error_path unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
  end

  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = show_message :expired
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.haml
= content_for :header_title, "Reset Password"
= content_for :header_subtitle, "Please enter your new password"
.row
  .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-12.mt-5.py-2.card
    .row
      .col-lg-8.offset-lg-2.col-12.my-3.cardbody
        = form_for(@user, url: password_reset_path(params[:id]), class: "row") do |f|
          = hidden_field_tag :email, @user.email
          .form-group
            = f.label :password
            .input-group
              .input-group-prepend
                %span.input-group-text#validationTooltipPasswordPrepend
                  = icon('fas', 'key', class: "regular")
              = f.password_field :password, class: "form-control is-valid rounded-right"
              .invalid-tooltip
                Please enter a valid password.
          .form-group
            = f.label :password_confirmation, "Repeat Password"
            .input-group
              .input-group-prepend
                %span.input-group-text#validationTooltipPasswordPrepend
                  = icon('fas', 'key', class: "regular")
              = f.password_field :password_confirmation, class: "form-control is-valid rounded-right"
              .invalid-tooltip
                Please enter the same password.
          .form-group    
            = f.submit "Update password", class: "btn col-4 btn-primary font-weight-bold"

app/views/password_resets/new.html.haml
= content_for :header_title, "Reset Password"
= content_for :header_subtitle, "Please enter your email"
.row
  .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-12.card
    .row
      .col-lg-8.offset-lg-2.col-12.my-3.cardbody
        = form_for(:reset_password, url: password_resets_path, class: "row") do |f|
          .form-group
            = f.label :email
            .input-group
              .input-group-prepend
                %span.input-group-text#validationTooltipEmailPrepend
                  @
              = f.text_field :email, class: "form-control is-valid", type: "email"
              .invalid-tooltip
                Please enter an existing email.
          .form-group    
            = f.submit "Submit", class: "btn col-4 btn-primary font-weight-bold"