config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  # root page
  root "static_pages#home"
  # static pages routes
  get "/help",    to: "static_pages#about", as: "helf"
  get "/about",   to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  # for new user
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  # for sign in
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # show all user's posts
  get "/user/posts/:id", to: "posts#posts", as: "user_posts"
  # error page
  get "/error", to: "static_pages#error"

  # adding REST architecture
  resources :users do
    # member return id
    # collection returns the obj
    member do
      get :following, :followers
    end
  end

  # Resources for the reset password and activation path
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new edit update create]
  resources :posts,               only: %i[create destroy]
  resources :relationships,       only: %i[create destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  # Aka followed
  # # This is going to return the relationship object (fw_id;fd_id)
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  # Aka followers
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  #  ! NEED TO LEARN IN DEPTH THIS CONCEPT!
  # # This is going to return the User object taken by the id of the relationship
  has_many :following, through: :active_relationships, source: :followed
  # Here the source can be omitted because Rails singularize the object to 'follower' so it is not needed
  has_many :followers, through: :passive_relationships, source: :follower
  # Cookie token
  attr_accessor :remember_token, :activation_token, :reset_token

  # Reference method
  before_create :create_activation_digest
  # Block type; with banger → self.email = self.email.downcase
  before_save :downcase_email

  # Profile Picture uploader
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, length: {minimum: 4, maximum: 32}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 80},
                          format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 8, maximum: 32}, allow_nil: true

  validates :bio, presence: true, length: {minimum: 4, maximum: 140}

  validate :picture_size

  # A method that uses bcrypt gem to secure the password via a digest
  has_secure_password

  # static functions
  class << self
      # return the hash of the string
      def digest string
        # This line is an compacted if; also it is created a local var "cost" that gets the value of the "min_cost" attribute
        # After ? there is the code executed if the result is true
        # After : there is the false expression
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # return a 22 lenth token
      def new_token
        SecureRandom.urlsafe_base64
      end
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def forget
    update remember_digest: nil
  end

  # This checks the remember digest saved on the cookie if match with the remember token
  def authenticated?(attribute, token)
    # meta programming; It can calls different methods (self.remember_digest, self.activation_digest)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update activated: true, activated_at: Time.zone.now
  end

  def send_notification_email(post)
    UserMailer.notification_post(self, post).deliver_now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    # Escaping the id
    Post.where("user_id = ?", id)
    # The same as 'posts'
  end

  def follow(other_user)
    # same as following.push(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def increment_sign_in
    increment!(:sign_in_count)
  end

  def sign_in_at
    update current_sign_in_at: Time.now.utc
  end

  def sign_in_ip(ip)
    update current_sign_in_ip: ip
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end

  def picture_size
    errors[:avatar] << "Should be less than 5 Mb." if avatar.size > 5.megabytes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: %i[index edit update destroy show following followers]
  before_action :correct_user,    only: %i[edit update]
  before_action :admin_user,      only: :destroy

  def index
    @users = User.where(activated: true).paginate page: params[:page], per_page: 18
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params)
    # Updating Bio here because form is shared
    @user.bio = "I am proud to be an user of Truth Side, aren't you?"
    if @user.save
      @user.send_activation_email
      cookies.permanent[:version] = current_version
      # ! Strange behariour: when redirect the hash symbol become a hash string!
      flash[:info] = show_message(:email, @user)
      redirect_to login_path
    else
      flash.now[:danger] = show_message(:form, @user)
      render "new"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = show_message(:destroyed)
    redirect_to users_url
  end

  def show
    @user = User.find(params[:id])
    @post = current_user.posts.build
    if news = show_version(cookies)
      @news = news
    end
    redirect_to root_url && return unless @user.activated?
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(permitted_params)
      flash[:success] = show_message(:edit, @user)
      redirect_to @user
    else
      flash.now[:danger] = show_message(:form, @user)
      render "edit"
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @all_users = @user.following
    # active_relationships is linked with Relationship class, that is why rails is searching for _relationship template
    @users = @all_users.paginate page: params[:page], per_page: 18
    if @users.any?
      render 'show_follow'
    else
      flash[:warning] = show_message(:no_follow)
      redirect_to @user
    end
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @all_users = @user.followers
    @users = @all_users.paginate page: params[:page], per_page: 18
    if @users.any?
      render 'show_follow'
    else
      flash[:warning] = show_message(:no_follow)
      redirect_to @user
    end
  end

  private

  # This method ensure the correct behaviour and minimize possible attacks, like param: admin=1
  def permitted_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :bio)
  end

  # Before filters

  def admin_user
    redirect_to error_path unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: "large", clas: "")
    img = user.avatar.send(size).url
    image_tag(img, alt: user.name, class: "img-fluid rounded gravatar #{clas}")
  end

  def capitalize(user)
    user.name.split.each(&:capitalize!).join(" ")
  end

  def show_message(option, _user=nil)
    case option
    when :form
      base = "The form contains " + "error".pluralize(_user.errors.count)
      ["CRAP!", "#{base}<ul><li>" + _user.errors.full_messages.join("</li><li>") + "</li></ul>".html_safe]
    when :greetings
      ["Welcome #{_user.name.capitalize}", "You will enjoy our platform full of truth segrets!"]
    when :edit
      ["Nice #{_user.name.capitalize}!", "Your informations were updated!"]
    when :login_invalid
      ["CRAP!", "Invalid email/password combination"]
    when :login_required
      ["DAMN!", "You need to login to continue."]
    when :destroyed
      ["HURRA!", "I cleaned some unneeded bytes."]
    when :email
      ["ALMOST!", "Please #{_user.name.capitalize} check your email to activate your account!"]
    when :wrong_activation
      ["DAMN!!", "Invalid activation link"]
    when :non_activated
      ["ALMOST!", "Your account is not activated, please check your email for the activation link"]
    when :email_sent
      ["YEAH!", "An email was sent to your account"]
    when :email_not_found
      ["CRAP!", "Email was not found!"]
    when :success_password
      ["YUPPY!", "The password was setted correctly!"]
    when :expired
      ["F@#*!", "The link has expired"]
    when :no_posts
      ["C'MON!", "You don't have any post yet.\nPlease create one to access to that page."]
    when :no_follow
      ["ARGH!", "I know that feeling when you have that zero.."]
    when :post_saved
      ["YEAH!", "Let's take the whole world!"]
    end
  end
end

app/views/users/_edit_user_optionals.html.haml
.col-12.mb-1.h5.ttf-regular.text-secondary.text-uppercase
  Profile picture
.col-12
  = form_for @user, url: user_path do |f|
    .col-12.mb-2
      = gravatar_for(@user, clas: "border border-grey")
    .form-group.row.aligns-items-center.my-3
      .col-lg-6.offset-lg-3.col-md-6.offset-md-3.col-10.offset-1.custom-file
        = f.file_field :avatar, class: "custom-file-input", accept: "image/jpeg,image/gif,image/png,image/jpg"
        = f.label :avatar, "Choose a file...", class: "text-left custom-file-label text-truncate", id: "file-label"
    .col-12.my-4.h5.ttf-regular.text-secondary.text-uppercase
      Biography
    .form-group.row
      = f.text_area :bio, class: "form-control is-valid rounded col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-10 offset-1", placeholder: "Write something about yourself..."
      .invalid-tooltip
        The length should be into the range (4-140)
    .form-group.mt-5
      = f.submit "Update", class: "btn btn-primary ttf-bold col-4"
:javascript
  $('#user_avatar').bind('change', function() {
    // update label
    $head = this.files[0].name;
    $('#file-label').text($head);
    var size_mb = this.files[0].size/1024/1024;
    console.log(size_mb);
    if (size_mb > 2.0) {
      console.log("yes");
      alert('Exceeded the maximum file size. Please upload an image below 2 Mb');
    }
  });

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build, remote: true) do |f|
  = hidden_field_tag :followed_id, @user.id
  .form-group
    = f.submit "Follow", class: "btn btn-primary ttf-bold"

app/views/users/_follow_form.html.haml
- unless current_user?(user)
  .div#follow_form
    - if current_user.following?(user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.haml
= form_for @user, url: yield(:form_url) do |f|
  .form-group
    = f.label :name
    .input-group
      .input-group-prepend
        %span.input-group-text#validationTooltipEmailPrepend
          = icon('fas', 'user', class: "regular")
      = f.text_field :name, class: "form-control is-valid rounded-right"    
      .invalid-tooltip
        Please enter a valid name.
  .form-group
    = f.label :email
    .input-group
      .input-group-prepend
        %span.input-group-text#validationTooltipEmailPrepend
          = icon('fas', 'envelope', class: "regular")
      = f.email_field :email, class: "form-control is-valid rounded-right"
      .invalid-tooltip
        Please enter a correct email.
  .form-group
    = f.label :password
    .input-group
      .input-group-prepend
        %span.input-group-text#validationTooltipPasswordPrepend
          = icon('fas', 'key', class: "regular")
      = f.password_field :password, class: "form-control is-valid rounded-right"
      .invalid-tooltip
        Please enter a valid password.
  .form-group
    = f.label :password_confirmation, "Repeat Password"
    .input-group
      .input-group-prepend
        %span.input-group-text#validationTooltipPasswordPrepend
          = icon('fas', 'key', class: "regular")
      = f.password_field :password_confirmation, class: "form-control is-valid rounded-right"
      .invalid-tooltip
        Please enter the same password.
  .form-group
    = f.submit yield(:button_text), class: "btn btn-primary ttf-bold"

app/views/users/_post_reminder.html.haml
.card
  .card-body
    .card-title.h3.ttf-regular.text-primary
      Hi mate
    .card-subtitle.text-muted
      Feature reminder
    .card-text.mt-2.h5
      I am a small helper that will introduce the site with some useful tips.
      .mt-2.ttf-regular.text-primary
        Let's see the new homepage!
    = link_to('Post it!', root_path, class: "ttf-bold btn btn-primary card-link")

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true ) do |f|  
  .form-group
    = f.submit "Unfollow", class: "btn btn-secondary ttf-bold"

app/views/users/_user.html.haml
%li
  .col-6.offset-3.card.my-1
    .row.card-body.mx-auto
      .col-12.mb-2
        = gravatar_for(user, size: :medium, clas: "img-fluid border border-grey")
      .col-12.h4.mt-3.ttf-regular.my-auto.text-capitalize            
        = link_to(user.name, user)
      - if current_user.admin? && !current_user?(user)
        .col-2.offset-5.bg-color-grey.border.my-2
        .col-12.ttf-bold.text-uppercase
          = link_to('delete', user, method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' })

app/views/users/edit.html.haml
- provide(:title, "Edit")
- provide(:button_text, "Save changes")
- provide(:form_url, user_path)
= content_for :header_title, "Edit"
= content_for :header_subtitle, "Here you can change your identity"
.row
  .col-lg-5.col-12.mx-auto.mb-2.py-3.card
    .row.card-body
      .col-12.card-title.h4.ttf-regular.text-primary.text-uppercase
        Optional Informations
      = render 'edit_user_optionals'
      
  .col-lg-5.col-12.mx-auto.mb-2.card
    .row.card-body
      .col-lg-10.offset-lg-1.col-md-10.offset-md-1.col-10.offset-1.my-3.text-center
        .h4.ttf-regular.text-primary.text-uppercase
          Important Information
        = render 'form'

app/views/users/index.html.haml
- provide :title, 'Users'
= content_for :header_title, "Users"
= content_for :header_subtitle, "Our beloved friends"
.row.align-items-center
  .col-12
    .card
      .card-body.align-center        
        %ul.list-unstyled
          -# THIS IS TOTALLY AWESOME!
          -# a block compacted to the var
          = render @users
        = will_paginate list_classes: %w(nav justify-content-center mt-4)
        

app/views/users/new.html.haml
- provide(:title, "Sign Up")
- provide(:button_text, "Create my account")
- provide(:form_url, signup_path)
= content_for :header_title, "Sign Up"
= content_for :header_subtitle, "Here you can start your journey"
.row
  .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-10.offset-1.mt-5.py-2.card
    .cardbody
      .col-lg-10.offset-lg-1.col-md-10.offset-md-1.col-12.mt-2        
        = render 'form'

app/views/users/show.html.haml
- provide :title, @user.name
= content_for :form_url, posts_path
= content_for :header_title, "User"

-# Needed because it will show the reminder also on other profile pages even if I'm not the owner
-# Only if the user has not posts
- if correct_user? 
  = content_for :header_subtitle, "Info about Myself"
  - unless current_user.feed.any?
    .row.my-3
      .col-lg-4.offset-lg-4.col-md-6.offset-md-3.col-10.offset-1
        = render 'post_reminder'
- else
  = content_for :header_subtitle, "Info about #{capitalize(@user)}"
.row.mb-2
  .col-lg-6.col-12.card.mx-auto
    .row.card-body.justify-content-center
      = render partial: '/shared/user_info', locals: { user: @user, font_size: 2, img_size: :large }
      = render partial: "/shared/stats", locals: { user: @user, font_size: 1.3 }        
      .row
        .col-12.mt-2
          = render partial: '/shared/user_optionals', locals: { user: @user }
        - if correct_user?
          .col-2.offset-5.bg-color-grey.rounded.mb-4
          .col-12 
            = link_to 'Settings', edit_user_path(@user), class: 'btn btn-primary'
        - else
          .col-2.offset-5.bg-color-grey.rounded.mb-4
          .col-12 
            = render partial: 'follow_form', locals: { user: @user }
  - if correct_user?
    .col-lg-6.col-12.card
      .row.card-body.p-3
        .col-12.card-title.h2.ttf-regular.text-capitalize
          New post
        .col-11.mx-auto
          = render partial: '/shared/post_form', locals: { post: @post }
- if @user.feed.any?
  .row.mb-2
    .col-lg-10.offset-lg-1.col-12.card
      .card-body.p-3
        .h1.mb-2.ttf-regular
          Recent Posts
        - @user.feed.order(created_at: :desc).last(3).each do |post|
          %ul.list-unstyled
            = render partial: '/posts/post', locals: { post: post } 
        - if @user.feed.count >= 3
          .col-12.mt-3.ttf-regular.text-uppercase
            = link_to('Show all', user_posts_path, class: "btn btn-outline-primary align-middle")
                

          
          

app/views/users/show_follow.html.haml
- provide :title, @title
= content_for :header_title, capitalize(@user)
= content_for :header_subtitle, @title
.row.mb-3
  .col-lg-3.col-12.mx-auto
    .card
      .card-body.row.justify-content-center
        = render partial: '/shared/user_info', locals: { user: @user, font_size: 1.5, img_size: :medium }
        = render partial: "/shared/stats", locals: { user: @user, font_size: 1 }
        .col-12.mt-2
          = link_to("Profile", @user, class: "btn btn-primary ttf-regular")
        - if @all_users.any?
          .col-12.mt-2.p-2
            - @all_users.each do |user|
              = link_to(gravatar_for(user, size: :small, clas: "img-fluid border border-primary rounded"), user)
  - if @all_users.any?
    .col-lg-9.col-12.card.p-3
      .card-body.align-center        
        .col-12.h2.ttf-regular.text-primary.text-uppercase.my-auto
          = @title.upcase
        %ul.list-unstyled
          = render @users
        = will_paginate list_classes: %w(nav justify-content-center mt-4)