config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  # root page
  root "static_pages#home"
  # static pages routes
  get "/help",    to: "static_pages#about", as: "helf"
  get "/about",   to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  # for new user
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  # for sign in
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # show all user's posts
  get "/user/posts/:id", to: "posts#posts", as: "user_posts"
  # error page
  get "/error", to: "static_pages#error"

  # adding REST architecture
  resources :users do
    # member return id
    # collection returns the obj
    member do
      get :following, :followers
    end
  end

  # Resources for the reset password and activation path
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new edit update create]
  resources :posts,               only: %i[create destroy]
  resources :relationships,       only: %i[create destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_messages.html.haml
#message_explanation
  -flash.each do |type,hash|            
    %div.m-3{ class: "alert alert-#{type} text-justify", role: "alert" }
      %h4.alert-heading.ttf-bold
        = hash[0].html_safe
      = hash[1].html_safe

app/views/shared/_popper.html.haml
#versionTruthCenter.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "versionTruth", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-dialog-centered{:role => "document"}
    .modal-content
      .modal-header
        %h5#versionTruthLongTitle.modal-title.ttf-regular What's new in this update!
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body.my-4
        = news
      .modal-footer
        %button.btn.btn-primary{"data-dismiss" => "modal", :type => "button"} Close

:javascript
  $(document).ready(function(){
    $('#versionTruthCenter').modal('show');
  });

app/views/shared/_post_form.html.haml
.card.rounded
  .card-body.pb-1
    = form_for post, url: yield(:form_url) do |f|
      .form-group.row.align-items-center
        = f.label :title, class: "col-lg-2 col-md-2 col-12 text-primary ttf-bold mb-0"
        = f.text_field :title, class: "form-control is-valid rounded col-lg-8 col-md-8 col-10 offset-1", placeholder: "Title"
        .invalid-tooltip
          The length should be into the range (4-88)
      .form-group.row.align-items-center
        = f.label :content, class: "col-lg-2 col-md-2 col-12 text-primary ttf-bold mb-0"
        = f.text_area :content, class: "form-control is-valid rounded col-lg-8 col-md-8 col-10 offset-1", placeholder: "Write something interesting..."
        .invalid-tooltip
          The length should be into the range (4-255)
      .form-group.row.aligns-items-center
        .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-10.offset-1.custom-file
          = f.file_field :picture, class: "custom-file-input", accept: "image/jpeg,image/gif,image/png,image/jpg"
          = f.label :picture, "Choose a file...", class: "text-left custom-file-label text-truncate", id: "file-label"
      .form-group
        = f.submit "Post", class: "btn btn-primary ttf-bold col-4"
:javascript
  $('#post_picture').bind('change', function() {
    // update label
    $head = this.files[0].name;
    $('#file-label').text($head);
    var size_mb = this.files[0].size/1024/1024;
    console.log(size_mb);
    if (size_mb > 5.0) {
      console.log("yes");
      alert('Exceeded the maximum file size. Please upload an image below 5 Mb');
    }
  });

    

app/views/shared/_stats.html.haml
.row.ttf-regular.w-100{ style: "font-size:#{font_size}em"}
  .col-6
    = link_to("<b id=\"followers\">#{user.followers.count}</b><br>Followers".html_safe, followers_user_path(user))
  .col-6
    = link_to("<b id=\"following\">#{user.following.count}</b><br>Following".html_safe, following_user_path(user))

app/views/shared/_user_info.html.haml
.col-12= gravatar_for(user, size: img_size, clas: "img-fluid border border-primary rounded")
.col-12.ttf-bold.mt-3
  .list-inline.align-text-bottom
    .list-inline-item.text-primary.mr-2{ style: "font-size: #{font_size}em"}
      = "#{user.name}"
    %span.list-inline-item.text-secondary
      = "#{user.posts.count} Posts"

app/views/shared/_user_optionals.html.haml
.justify-content-center
  %table.mx-auto
    %tbody.text-center
      - user.attributes.each do |attr|          
        - if %w[bio].include?(attr[0])
          %tr
            %td.h5.ttf-regular.text-primary
              = attr[0].upcase
          %tr
            %td.p-3
              = attr[1]