config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  # root page
  root "static_pages#home"
  # static pages routes
  get "/help",    to: "static_pages#about", as: "helf"
  get "/about",   to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  # for new user
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  # for sign in
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # show all user's posts
  get "/user/posts/:id", to: "posts#posts", as: "user_posts"
  # error page
  get "/error", to: "static_pages#error"

  # adding REST architecture
  resources :users do
    # member return id
    # collection returns the obj
    member do
      get :following, :followers
    end
  end

  # Resources for the reset password and activation path
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new edit update create]
  resources :posts,               only: %i[create destroy]
  resources :relationships,       only: %i[create destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer.row.text-center.bg-dark.text-white.rounded-bottom
  .col-12
    .py-4.ttf-light
      This site was created by
      .text-danger.ttf-bold
        Yeboster
      for other examples please visit this
      = link_to "Page", "https://yeboster.club", class: "col-12 text-danger nounderline ttf-bold"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.nav-bg.my-2
  %a.navbar-brand.ttf-regular.text-primary{:href => "/"}
    %svg#logo.img-fluid.mr-1.d-inline-block{:preserveaspectratio => "xMinYMin", :viewbox => "0 0 7.6 16.1"}
      %g#Layer_2{"data-name" => "Layer 2", :xmlns => "http://www.w3.org/2000/svg"}
        %g#S_Image{"data-name" => "S Image"}
          %path{:d => "M.19,8.32a.34.34,0,0,1,.08-.21L3.36,4.68,7.54,0,7.6.06l-6,8.18H6.07c.28,0,.4.12.4.4,0,.08,0,.17,0,.25H.19C.19,8.7.19,8.51.19,8.32Z"}
          %path{:d => "M7.41,7.78A.34.34,0,0,1,7.33,8L4.24,11.43.06,16.1,0,16,6,7.87H1.53c-.28,0-.4-.12-.4-.4,0-.08,0-.17,0-.25H7.41C7.41,7.41,7.41,7.59,7.41,7.78Z"}
    Truth Side
  #nav-support.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li{:class => "nav-item #{yield :active_home}"}
        = link_to "Home", root_path, class: "nav-link"
      %li{:class => "nav-item #{yield :active_about}"}
        = link_to "About", about_path, class: "nav-link"
      %li{:class => "nav-item #{yield :active_contact}"}
        = link_to "Contact", contact_path, class: "nav-link"
  .float-right
    - if logged_in?
      .dropdown.d-inline-block
        %a#navbarDropdown.dropdown-toggle.btn.btn-outline-primary.ttf-regular{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          My account
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          = link_to "Profile", current_user, class: "dropdown-item"
          = link_to "Settings", edit_user_path(current_user), class: "dropdown-item"
          = link_to "Users", users_path, class: "dropdown-item"
          - if current_user.posts.any?
            = link_to "Posts", user_posts_path(current_user), class: "dropdown-item"
          .dropdown-divider
          = link_to "Log out", logout_path, method: :delete, class: "dropdown-item ttf-bold text-danger"
    - elsif !current_page(request,login_path)
      .nav-item.d-inline-block
        = link_to "Log In", login_path, class: "btn btn-outline-primary ttf-regular"
    %button.navbar-toggler{"aria-controls" => "nav-support", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#nav-support", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags 
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' 
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

app/views/layouts/application.html.haml
%html
  %head
    %title
      = full_title yield :title
  = render 'layouts/rails_default'
  = render 'layouts/head-links'
  %body.bg-light
    .container-fluid
      - if @news
        = render partial: '/shared/popper', locals: {news: @news}
      = render 'layouts/navbar'
      .row.jumbotron.mb-0.text-center
        .col-12.mb-3
          .row
            .col-12.ttf-regular.text-uppercase.display-4
              = yield :header_title
            .col-12.h2.text-secondary
              = yield :header_subtitle
        .col-lg-6.offset-lg-3.col-md-8.offset-md-2.col-10.mb-2.offset-1
          = render '/shared/messages'
        .col-12
          = yield
      = render 'layouts/footer'
      = debug params if Rails.env.development?